pip3 install psutil
pip3 install shutil
pip3 install requests
pip3 install crypto
pip3 install platform
pip3 install sqlite3
pip3 install win32crypt
pip3 install nuitka
pip3 install pyinstaller
pip3 install pywin32
pip3 install pyqt5
pip3 install cryptography
